export const newMenu = [
  // {
  //   id: 1,
  //   text: "Dashboard",
  //   link: "/dashboard",
  //   icon: "",
  //   parent: 0,
  //   sequence: 1,
  //   permission: null,
  // },
  {
    id: 2,
    text: "Products",
    link: "",
    icon: "",
    parent: 0,
    sequence: 3,
    permission: null,
  },
  {
    id: 3,
    text: "Quotation",
    link: "",
    icon: "",
    parent: 0,
    sequence: 4,
    permission: null,
  },

  {
    id: 5,
    text: "View Products",
    link: "/view-products",
    icon: "",
    parent: 2,
    sequence: 1,
    permission: null,
  },
  {
    id: 6,
    text: "Add Products",
    link: "/add-products",
    icon: "",
    parent: 2,
    sequence: 2,
    permission: null,
  },
  {
    id: 7,
    text: "View Quotation",
    link: "/view-quotation",
    icon: "",
    parent: 3,
    sequence: 1,
    permission: null,
  },
  {
    id: 8,
    text: "Add Quotation",
    link: "/add-quotation",
    icon: "",
    parent: 3,
    sequence: 2,
    permission: null,
  },
  {
    id: 10,
    text: "User",
    link: "",
    icon: "",
    parent: 0,
    sequence: 3,
    permission: null,
  },
  {
    id: 11,
    text: "View User",
    link: "/view-user",
    icon: "",
    parent: 10,
    sequence: 1,
    permission: null,
  },
  {
    id: 12,
    text: "Add User",
    link: "/add-user",
    icon: "",
    parent: 10,
    sequence: 2,
    permission: null,
  },
  {
    id: 13,
    text: "Customer",
    link: "/view-customer",
    icon: "",
    parent: 0,
    sequence: 3,
    permission: null,
  },
  {
    id: 14,
    text: "Sales Order",
    link: "",
    icon: "",
    parent: 0,
    sequence: 5,
    permission: null,
  },
  {
    id: 15,
    text: "View Sales Order",
    link: "/view-salesorder",
    icon: "",
    parent: 14,
    sequence: 1,
    permission: null,
  },
  {
    id: 16,
    text: "Add Sales Order",
    link: "/add-salesorder",
    icon: "",
    parent: 14,
    sequence: 2,
    permission: null,
  },
  {
    id: 17,
    text: "Procurement",
    link: "/purchase-order",
    icon: "",
    parent: 0,
    sequence: 6,
    permission: null,
  },
  {
    id: 18,
    text: "Order Processing",
    link: "/order-processing",
    icon: "",
    parent: 14,
    sequence: 3,
    permission: null,
  },
  {
    id: 19,
    text: "Asset Mgmt",
    link: "",
    icon: "",
    parent: 0,
    sequence: 8,
    permission: null,
  },
  {
    id: 20,
    text: "View Asset",
    link: "/view-asset",
    icon: "",
    parent: 19,
    sequence: 1,
    permission: null,
  },
  {
    id: 21,
    text: "Add Asset",
    link: "/add-asset",
    icon: "",
    parent: 19,
    sequence: 2,
    permission: null,
  },

  {
    id: 23,
    text: "Data Setup",
    icon: "",
    parent: 0,
    sequence: 2,
    permission: null,
  },
  {
    id: 24,
    text: "View Purchase Order",
    link: "/view-purchase-order",
    icon: "",
    parent: 17,
    sequence: 1,
    permission: null,
  },
  {
    id: 25,
    text: "GRN",
    link: "/grn",
    icon: "",
    parent: 17,
    sequence: 2,
    permission: null,
  },
  {
    id: 26,
    text: "Supplier",
    link: "/view-supplier",
    icon: "",
    parent: 17,
    sequence: 3,
    permission: null,
  },
  {
    id: 27,
    text: "Master Data Setup",
    link: "/master-data-setup",
    icon: "",
    parent: 23,
    sequence: 1,
    permission: null,
  },
  {
    id: 28,
    text: "System Option",
    link: "",
    icon: "",
    parent: 23,
    sequence: 2,
    permission: null,
  },
  {
    id: 29,
    text: "Payment",
    icon: "",
    parent: 0,
    sequence: 7,
    permission: null,
  },
  {
    id: 30,
    text: "Payable",
    link: "/payable",
    icon: "",
    parent: 29,
    sequence: 0,
    permission: null,
  },
  {
    id: 31,
    text: "Receivable",
    link: "/receivable",
    icon: "",
    parent: 29,
    sequence: 1,
    permission: null,
  },
  {
    id: 32,
    text: "Organisation Profile",
    link: "/addOrganisation",
    parent: 23,
    sequence: 3,
    permission: null,
  },
  {
    id: 33,
    text: "Settings",
    icon: "i-Gear-2",
    parent: 0,
    sequence: 10,
    permission: null,
  },
  {
    id: 34,
    text: "Module",
    link: "/module",
    parent: 33,
    sequence: 1,
    permission: null,
  },
  {
    id: 35,
    text: "Sub Module",
    link: "/sub-module",
    parent: 33,
    sequence: 2,
    permission: null,
  },

  {
    id: 36,
    text: "Access Management",
    link: "/access-management",
    icon: "i-Full-View-Window",
    parent: 0,
    sequence: 11,
    permission: null,
  },
  {
    id: 37,
    text: "Reports",
    icon: "",
    parent: 0,
    sequence: 12,
    permission: null,
  },
  {
    id: 38,
    text: "Sales Report",
    link: "/sales-report",
    parent: 37,
    sequence: 6,
    permission: null,
  },
  {
    id: 39,
    text: "Inventory Stock",
    link: "/inventory-stock",
    parent: 37,
    sequence: 7,
    permission: null,
  },
  {
    id: 40,
    text: "Stock Movement",
    link: "/inventory-stock-movement",
    parent: 37,
    sequence: 8,
    permission: null,
  },
  {
    id: 41,
    text: "Expense Report",
    link: "/expense-report",
    parent: 37,
    sequence: 9,
    permission: null,
  },
  {
    id: 42,
    text: "Delivery Report",
    link: "/delivery-report",
    parent: 37,
    sequence: 10,
    permission: null,
  },
  {
    id: 43,
    text: "Quotation",
    parent: 37,
    sequence: 1,
    permission: null,
  },
  {
    id: 44,
    text: "Summary Report",
    link: "/summary-report",
    parent: 43,
    sequence: 1,
    permission: null,
  },
  {
    id: 45,
    text: "Follow-Up Listing",
    link: "/followup-listing",
    parent: 43,
    sequence: 2,
    permission: null,
  },
  {
    id: 46,
    text: "History By Product",
    link: "/history-product",
    parent: 43,
    sequence: 3,
    permission: null,
  },
  {
    id: 47,
    text: "History By Customer",
    link: "/history-customer",
    parent: 43,
    sequence: 4,
    permission: null,
  },
  {
    id: 48,
    text: "Order Entry",
    parent: 37,
    sequence: 2,
    permission: null,
  },
  {
    id: 49,
    text: "Outstanding O/E Listing",
    link: "/outstanding",
    parent: 48,
    sequence: 1,
    permission: null,
  },
  {
    id: 50,
    text: "Sales Booking by Sales Person",
    link: "/sales-booking",
    parent: 48,
    sequence: 2,
    permission: null,
  },
  {
    id: 51,
    text: "Inventory Forecast",
    link: "/inventory-forecast",
    parent: 48,
    sequence: 3,
    permission: null,
  },
  {
    id: 52,
    text: "Purchase Order",
    parent: 37,
    sequence: 3,
    permission: null,
  },
  {
    id: 53,
    text: "PO Listing",
    link: "/purchase-listing",
    parent: 52,
    sequence: 1,
    permission: null,
  },
  {
    id: 54,
    text: "Details PO Listing",
    link: "/details-purchase-listing",
    parent: 52,
    sequence: 2,
    permission: null,
  },
  {
    id: 55,
    text: "Outstanding Purchase order Listing",
    link: "/outstanding-listing",
    parent: 52,
    sequence: 3,
    permission: null,
  },
  {
    id: 56,
    text: "Outstanding Details Purchase order Listing",
    link: "/details-outstanding-listing",
    parent: 52,
    sequence: 4,
    permission: null,
  },
  {
    id: 57,
    text: "GRN",
    parent: 37,
    sequence: 4,
    permission: null,
  },
  {
    id: 58,
    text: "GRN Listing",
    link: "/grn-listing",
    parent: 57,
    sequence: 1,
    permission: null,
  },
  {
    id: 59,
    text: "Details GRN Listing",
    link: "/details-grn-listing",
    parent: 57,
    sequence: 2,
    permission: null,
  },
  {
    id: 60,
    text: "Unpost GRN Listing",
    link: "/unpost-grn-listing",
    parent: 57,
    sequence: 3,
    permission: null,
  },
  {
    id: 61,
    text: "Unpost Details GRN Listing",
    link: "/details-unpost-listing",
    parent: 57,
    sequence: 4,
    permission: null,
  },
  {
    id: 62,
    text: "Product Analyst Supplier",
    link: "/grn-product-supplier",
    parent: 57,
    sequence: 5,
    permission: null,
  },
  {
    id: 63,
    text: "Product Analyst Product",
    link: "/grn-product",
    parent: 57,
    sequence: 6,
    permission: null,
  },
  {
    id: 64,
    text: "GRN Batch Lot Details",
    link: "/grn-batch",
    parent: 57,
    sequence: 7,
    permission: null,
  },
  {
    id: 65,
    text: "Inventory Stock",
    parent: 37,
    sequence: 5,
    permission: null,
  },
  {
    id: 66,
    text: "Stock Card",
    link: "/stock-card",
    parent: 65,
    sequence: 1,
    permission: null,
  },
  {
    id: 67,
    text: "Stock Detail Listing",
    link: "/stock-details-listing",
    parent: 65,
    sequence: 2,
    permission: null,
  },
  {
    id: 68,
    text: "Stock Status",
    link: "/stock-status",
    parent: 65,
    sequence: 3,
    permission: null,
  },
  {
    id: 69,
    text: "Temporary Stock Transaction History",
    link: "/temp-stock-transaction-history",
    parent: 65,
    sequence: 4,
    permission: null,
  },
  {
    id: 70,
    text: "FIFO Stock Valuation",
    link: "/fifo-stock-valuation",
    parent: 65,
    sequence: 5,
    permission: null,
  },
  {
    id: 71,
    text: "Aging of Stock List",
    link: "/aging-stock-list",
    parent: 65,
    sequence: 6,
    permission: null,
  },
  {
    id: 72,
    text: "Re-order Report",
    link: "/re-order-report",
    parent: 65,
    sequence: 7,
    permission: null,
  },
  {
    id: 73,
    text: "Activity Log Report",
    link: "/activity-log-report",
    parent: 37,
    sequence: 10,
    permission: null,
  },
  {
    id: 75,
    text: "Delivery Management",
    link: "/delivery-management",
    icon: "",
    parent: 0,
    sequence: 13,
    permission: null,
  },
  {
    id: 76,
    text: "Delivery Schedule",
    link: "/delivery-schedule",
    parent: 75,
    sequence: 14,
    permission: null,
  },
  {
    id: 77,
    text: "Delivery",
    link: "/delivery",
    icon: "i-Full-View-Window",
    parent: 75,
    sequence: 11,
    permission: null,
  },
  {
    id: 78,
    text: "Warehouse",
    link: "",
    icon: "",
    parent: 0,
    sequence: 14,
    permission: null,
  },
  {
    id: 79,
    text: "Product Tagging",
    link: "/product-tagging",
    icon: "",
    parent: 78,
    sequence: 1,
    permission: null,
  },
  {
    id: 80,
    text: "Stock",
    link: "/stock",
    icon: "",
    parent: 78,
    sequence: 2,
    permission: null,
  },
  {
    id: 81,
    text: "Storage Area",
    link: "/storage-area",
    icon: "",
    parent: 78,
    sequence: 3,
    permission: null,
  },
  {
    id: 82,
    text: "Product Master",
    link: "/product-master",
    icon: "",
    parent: 78,
    sequence: 4,
    permission: null,
  },
  {
    id: 83,
    text: "Pricelist Setup",
    link: "/price-list",
    icon: "",
    parent: 2,
    sequence: 2,
    permission: null,
  },
  {
    id: 84,
    text: "Purchase Expenses",
    link: "/purchase-expense",
    icon: "",
    parent: 29,
    sequence: 3,
    permission: null,
  },
];
export const permissions = ["view-user", "add-user", "view-customer", "add-customer", "supplier-info"];
